const mongoose = require("mongoose");
const _ = require("lodash");
var mongoose_delete = require("mongoose-delete");
var OrderSchema = mongoose.Schema({
    quotation_id: { type: mongoose.Schema.Types.ObjectId, ref: 'quotation', required: true },
    material_id: {
        type: String,
        required: true,
    },
    cart_id: {
        type: String,
        required: true,
    },
    order_id: {
        type: String,
        required: false,
    },
    zendesk_ticket_id: {
        type: String,
        required: false,
    },
    transaction_id: {
        type: String,
        required: false,
    },
    first_name: {
        type: String,
        required: false,
    },
    last_name: {
        type: String,
        required: false,
    },
    email: {
        type: String,
        required: true,
    },
    phone_number: {
        type: String,
        required: false,
    },
    color: {
        type: String,
        required: true,
    },
    amount: {
        type: String,
        required: true,
    },
    payment_status: {
        type: String,
        enum: ['Pending', 'Completed', 'Failed'],  // Restrict to these values
        default: 'Pending'
    },
    
    deleted: {
        type: Boolean,
        required: false,
        default: false,
    },
    createdAt: {
        type: Date,
        default: Date.now(),
    },
    
});
OrderSchema.set("toObject", { getters: true });
OrderSchema.set("toJSON", { getters: true });

OrderSchema.changeLog = true;

OrderSchema.plugin(mongoose_delete);
OrderSchema.plugin(mongoose_delete, { overrideMethods: "all" });
OrderSchema.fillable = ["quotation_id","material_id","cart_id","order_id","zendesk_ticket_id","transaction_id","first_name","last_name","email","phone_number","color","amount","payment_status"];

OrderSchema.customFields = {
    _id: {
        field_name: "_id",
        db_name: "_id",
        type: "text",
        placeholder: "Id",
        listing: true,
        show_in_form: false,
        sort: true,
        default_sort: true,
        required: false,
        value: "",
        width: "50",
        searchable: false,
    },
    quotation_id: {
        field_name: "quotation_id",
        db_name: "quotation_id",
        type: "text",
        placeholder: "quotation_id",
        listing: true,
        sort: true,
        default_sort: false,
        required: false,
        value: "",
        width: "50",
        searchable: false,
    },
    material_id: {
        field_name: "material_id",
        db_name: "material_id",
        type: "text",
        placeholder: "material_id",
        listing: true,
        sort: true,
        default_sort: false,
        required: false,
        value: "",
        width: "50",
        searchable: true,
    },
    order_id: {
        field_name: "order_id",
        db_name: "order_id",
        type: "text",
        placeholder: "order_id",
        listing: true,
        sort: true,
        default_sort: false,
        required: false,
        value: "",
        width: "50",
        searchable: true,
    },
    zendesk_ticket_id: {
        field_name: "zendesk_ticket_id",
        db_name: "zendesk_ticket_id",
        type: "text",
        placeholder: "zendesk_ticket_id",
        listing: true,
        sort: true,
        default_sort: false,
        required: false,
        value: "",
        width: "50",
        searchable: true,
    },
    cart_id: {
        field_name: "cart_id",
        db_name: "cart_id",
        type: "text",
        placeholder: "cart_id",
        listing: true,
        sort: true,
        default_sort: false,
        required: false,
        value: "",
        width: "50",
        searchable: true,
    },
    transaction_id: {
        field_name: "transaction_id",
        db_name: "transaction_id",
        type: "text",
        placeholder: "transaction_id",
        listing: true,
        sort: true,
        default_sort: false,
        required: false,
        value: "",
        width: "50",
        searchable: true,
    },
    first_name: {
        field_name: "first_name",
        db_name: "first_name",
        type: "text",
        placeholder: "first_name",
        listing: true,
        sort: true,
        default_sort: false,
        required: false,
        value: "",
        width: "50",
        searchable: true,
    },
    last_name: {
        field_name: "last_name",
        db_name: "last_name",
        type: "text",
        placeholder: "last_name",
        listing: true,
        sort: true,
        default_sort: false,
        required: false,
        value: "",
        width: "50",
        searchable: true,
    },
    email: {
        field_name: "email",
        db_name: "email",
        type: "text",
        placeholder: "Email",
        listing: true,
        sort: true,
        default_sort: false,
        required: true,
        value: "",
        width: "50",
        searchable: true,
    },
    phone_number: {
        field_name: "phone_number",
        db_name: "phone_number",
        type: "text",
        placeholder: "phone_number",
        listing: true,
        sort: true,
        default_sort: false,
        required: false,
        value: "",
        width: "50",
        searchable: true,
    },
    color: {
        field_name: "color",
        db_name: "color",
        type: "text",
        placeholder: "color",
        listing: true,
        sort: true,
        default_sort: false,
        required: false,
        value: "",
        width: "50",
        searchable: true,
    },
    amount: {
        field_name: "amount",
        db_name: "amount",
        type: "text",
        placeholder: "amount",
        listing: true,
        sort: true,
        default_sort: false,
        required: false,
        value: "",
        width: "50",
        searchable: true,
    },
    payment_status: {
        field_name: "payment_status",
        db_name: "payment_status",
        type: "text",
        placeholder: "payment_status",
        listing: true,
        sort: true,
        default_sort: false,
        required: false,
        value: "",
        width: "50",
        searchable: true,
    },

    createdAt: {
        "field_name": "createdAt",
        "db_name": "createdAt",
        "type": Date,
        "placeholder": "createdAt",
        "listing": true,
        "sort": true,
        "default_sort": false,
        "required": false,
        "value": "",
        "width": "50",
        "searchable": false
    },
};

module.exports = mongoose.model("orders", OrderSchema);
