const mongoose = require("mongoose");
const _ = require("lodash");
var mongoose_delete = require("mongoose-delete");
var OrderSchema = mongoose.Schema({
    quotation_id: { type: mongoose.Schema.Types.ObjectId, ref: 'quotation', required: true },
    material_id: {
        type: String,
        required: true,
    },
    cart_id: {
        type: String,
        required: false,
    },
    order_id: {
        type: String,
        required: false,
    },
    first_name: {
        type: String,
        required: false,
    },
    last_name: {
        type: String,
        required: false,
    },
    email: {
        type: String,
        required: true,
    },
    phone_number: {
        type: String,
        required: false,
    },
    colors: {
        type: Object,
        default: {},
    },
    amount: {
        type: String,
        required: true,
    },
    shipping_amount: {
        type: Number,
        required: false,
        default:0
    },
    total_amount: {
        type: Number,
        required: false,
        default:0
    },
    billing_address: {
        type: Object,
        required: false,
    },
    payment_status: {
        type: String,
        default: 'Pending'
    },
    order_status: {
        type: String,
        default: 'Pending'
    },
    is_mail_send: {
        type: Boolean,
        required: false,
        default: false
    },
    
    deleted: {
        type: Boolean,
        required: false,
        default: false,
    },
    createdAt: {
        type: Date,
        default: () => Date.now(), 
    },
    updatedAt: {
        type: Date,
        default: () => Date.now(), 
    },
    paymentDate: {
        type: Date,
        default: null, 
    },
    
});
OrderSchema.set("toObject", { getters: true });
OrderSchema.set("toJSON", { getters: true });

OrderSchema.changeLog = true;

OrderSchema.plugin(mongoose_delete);
OrderSchema.plugin(mongoose_delete, { overrideMethods: "all" });
OrderSchema.fillable = ["quotation_id","material_id","cart_id","order_id","first_name","last_name","email","phone_number","colors","amount","shipping_amount","total_amount","payment_status","billing_address"];

OrderSchema.customFields = {
    _id: {
        field_name: "_id",
        db_name: "_id",
        type: "text",
        placeholder: "Id",
        listing: true,
        show_in_form: false,
        sort: true,
        default_sort: true,
        required: false,
        value: "",
        width: "50",
        searchable: false,
    },
    quotation_id: {
        field_name: "quotation_id",
        db_name: "quotation_id",
        type: "text",
        placeholder: "quotation_id",
        listing: true,
        sort: true,
        default_sort: false,
        required: false,
        value: "",
        width: "50",
        searchable: false,
    },
    material_id: {
        field_name: "material_id",
        db_name: "material_id",
        type: "text",
        placeholder: "material_id",
        listing: true,
        sort: true,
        default_sort: false,
        required: false,
        value: "",
        width: "50",
        searchable: true,
    },
    order_id: {
        field_name: "order_id",
        db_name: "order_id",
        type: "text",
        placeholder: "order_id",
        listing: true,
        sort: true,
        default_sort: false,
        required: false,
        value: "",
        width: "50",
        searchable: true,
    },
    cart_id: {
        field_name: "cart_id",
        db_name: "cart_id",
        type: "text",
        placeholder: "cart_id",
        listing: true,
        sort: true,
        default_sort: false,
        required: false,
        value: "",
        width: "50",
        searchable: true,
    },
    first_name: {
        field_name: "first_name",
        db_name: "first_name",
        type: "text",
        placeholder: "first_name",
        listing: true,
        sort: true,
        default_sort: false,
        required: false,
        value: "",
        width: "50",
        searchable: true,
    },
    last_name: {
        field_name: "last_name",
        db_name: "last_name",
        type: "text",
        placeholder: "last_name",
        listing: true,
        sort: true,
        default_sort: false,
        required: false,
        value: "",
        width: "50",
        searchable: true,
    },
    email: {
        field_name: "email",
        db_name: "email",
        type: "text",
        placeholder: "Email",
        listing: true,
        sort: true,
        default_sort: false,
        required: true,
        value: "",
        width: "50",
        searchable: true,
    },
    phone_number: {
        field_name: "phone_number",
        db_name: "phone_number",
        type: "text",
        placeholder: "phone_number",
        listing: true,
        sort: true,
        default_sort: false,
        required: false,
        value: "",
        width: "50",
        searchable: true,
    },
    colors: {
        field_name: "color",
        db_name: "color",
        type: "text",
        placeholder: "color",
        listing: true,
        sort: true,
        default_sort: false,
        required: false,
        value: "",
        width: "50",
        searchable: true,
    },
    amount: {
        field_name: "amount",
        db_name: "amount",
        type: "text",
        placeholder: "amount",
        listing: true,
        sort: true,
        default_sort: false,
        required: false,
        value: "",
        width: "50",
        searchable: true,
    },
    shipping_amount: {
        field_name: "shipping_amount",
        db_name: "shipping_amount",
        type: "text",
        placeholder: "shipping_amount",
        listing: true,
        sort: true,
        default_sort: false,
        required: false,
        value: "",
        width: "50",
        searchable: true,
    },
    total_amount: {
        field_name: "total_amount",
        db_name: "total_amount",
        type: "text",
        placeholder: "total_amount",
        listing: true,
        sort: true,
        default_sort: false,
        required: false,
        value: "",
        width: "50",
        searchable: true,
    },
    payment_status: {
        field_name: "payment_status",
        db_name: "payment_status",
        type: "text",
        placeholder: "payment_status",
        listing: true,
        sort: true,
        default_sort: false,
        required: false,
        value: "",
        width: "50",
        searchable: true,
    },
    order_status: {
        field_name: "order_status",
        db_name: "order_status",
        type: "text",
        placeholder: "order_status",
        listing: true,
        sort: true,
        default_sort: false,
        required: false,
        value: "",
        width: "50",
        searchable: true,
    },
    billing_address: {
        field_name: "billing_address",
        db_name: "billing_address",
        type: "text",
        placeholder: "billing_address",
        listing: true,
        sort: true,
        default_sort: false,
        required: false,
        value: "",
        width: "50",
        searchable: true,
    },
 

    createdAt: {
        "field_name": "createdAt",
        "db_name": "createdAt",
        "type": Date,
        "placeholder": "createdAt",
        "listing": true,
        "sort": true,
        "default_sort": false,
        "required": false,
        "value": "",
        "width": "50",
        "searchable": false
    },
};

module.exports = mongoose.model("orders", OrderSchema);
